name: LobbyPlugin
version: '1.0-SNAPSHOT'
main: de.tayblocks.lobbyplugin.LobbyPlugin
api-version: 1.19
permissions:
  system.setspawn:
    default: op

commands:
  spawn:
    aliases: ["setspawn"]

  lobby:
